### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by rahulbanwasi** [vinayak-7-0-3/Tidal-DL-Telegram#16]
Tried usig elephant sql's database whose size is 20mb and i can see there only 300 kb was used but still the bot says database is locked. Here is the log

Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/Tidal-DL-Telegram/bot/__main__.py", line 45, in <module>
    app.run()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pyrogram/methods/utilities/run.py", line 80, in run
    run(self.start())
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/ec2-user/Tidal-DL-Telegram/bot/__main__.py", line 24, in start
    await super().start()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pyrogram/client.py", line 562, in load_session
    await self.storage.open()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pyrogram/storage/file_storage.py", line 63, in open
    self.update()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pyrogram/storage/file_storage.py", line 52, in update
    self.version(version)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pyrogram/storage/sqlite_storage.py", line 227, in version
    (value,)
sqlite3.OperationalError: database is locked

**Comment by vinayak-7-0-3** [comment]
Its not an issue with the PostgresSQL.
Its due to wrong or corrupted USER_SESSION
Please regenerate the user session and also recheck the telegram api id and api hash.

**Comment by rahulbanwasi** [comment]
again did that, not working. Still says database locked.

**Comment by rahulbanwasi** [comment]
also no it's not about the User_Session as earlier it was working without any user session. This time after you said i entered that too but still nothing.

**Comment by vinayak-7-0-3** [comment]
> also no it's not about the User_Session as earlier it was working without any user session. This time after you said i entered that too but still nothing.

Issue is related with Telegram session.
Try removing .session files and rerun the bot.
Also refer this - [Link](https://docs.pyrogram.org/faq/sqlite3-operationalerror-database-is-locked)
